# Generated by Django 5.0.2 on 2024-08-12 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('consultant', 'Consultant'), ('responsable', 'Responsable')], default='consultant', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requetes', to='gestion.company')),
                ('consultant', models.ForeignKey(limit_choices_to={'role': 'consultant'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_requetes', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(limit_choices_to={'role': 'responsable'}, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_requetes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requete',
                'verbose_name_plural': 'Requetes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialControlSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_livre_status', models.CharField(max_length=20)),
                ('grand_livre_comments', models.TextField(blank=True, null=True)),
                ('balance_comptes_status', models.CharField(max_length=20)),
                ('balance_comptes_comments', models.TextField(blank=True, null=True)),
                ('exhaustivite_pieces_status', models.CharField(max_length=20)),
                ('exhaustivite_pieces_comments', models.TextField(blank=True, null=True)),
                ('titres_participation_status', models.CharField(max_length=20)),
                ('titres_participation_comments', models.TextField(blank=True, null=True)),
                ('comptes_filiales_status', models.CharField(max_length=20)),
                ('comptes_filiales_comments', models.TextField(blank=True, null=True)),
                ('cout_acquisition_status', models.CharField(max_length=20)),
                ('cout_acquisition_comments', models.TextField(blank=True, null=True)),
                ('depreciation_calc_status', models.CharField(max_length=20)),
                ('depreciation_calc_comments', models.TextField(blank=True, null=True)),
                ('evaluation_titres_status', models.CharField(max_length=20)),
                ('evaluation_titres_comments', models.TextField(blank=True, null=True)),
                ('depots_cautionnements_status', models.CharField(max_length=20)),
                ('depots_cautionnements_comments', models.TextField(blank=True, null=True)),
                ('analyse_mouvements_status', models.CharField(max_length=20)),
                ('analyse_mouvements_comments', models.TextField(blank=True, null=True)),
                ('prets_accordes_status', models.CharField(max_length=20)),
                ('prets_accordes_comments', models.TextField(blank=True, null=True)),
                ('rapprochement_status', models.CharField(max_length=20)),
                ('rapprochement_comments', models.TextField(blank=True, null=True)),
                ('recensement_prets_status', models.CharField(max_length=20)),
                ('recensement_prets_comments', models.TextField(blank=True, null=True)),
                ('cut_off_status', models.CharField(max_length=20)),
                ('cut_off_comments', models.TextField(blank=True, null=True)),
                ('taux_interets_status', models.CharField(max_length=20)),
                ('taux_interets_comments', models.TextField(blank=True, null=True)),
                ('conventions_reglementees_status', models.CharField(max_length=20)),
                ('conventions_reglementees_comments', models.TextField(blank=True, null=True)),
                ('etats_synthese_status', models.CharField(max_length=20)),
                ('etats_synthese_comments', models.TextField(blank=True, null=True)),
                ('infos_etats_status', models.CharField(max_length=20)),
                ('infos_etats_comments', models.TextField(blank=True, null=True)),
                ('regles_methods_status', models.CharField(max_length=20)),
                ('regles_methods_comments', models.TextField(blank=True, null=True)),
                ('tableaux_a2a3_status', models.CharField(max_length=20)),
                ('tableaux_a2a3_comments', models.TextField(blank=True, null=True)),
                ('tableaux_b7b8_status', models.CharField(max_length=20)),
                ('tableaux_b7b8_comments', models.TextField(blank=True, null=True)),
                ('general_comments', models.TextField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_control_submissions', to='gestion.requete')),
            ],
        ),
    ]
