# Generated by Django 5.0.2 on 2024-08-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='analyse_mouvements_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='balance_comptes_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='comptes_filiales_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='conventions_reglementees_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='cout_acquisition_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='cut_off_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='depots_cautionnements_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='depreciation_calc_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='etats_synthese_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='evaluation_titres_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='exhaustivite_pieces_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='grand_livre_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='infos_etats_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='prets_accordes_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='rapprochement_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='recensement_prets_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='regles_methods_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='tableaux_a2a3_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='tableaux_b7b8_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='taux_interets_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialcontrolsubmission',
            name='titres_participation_status',
            field=models.CharField(choices=[('Fait', 'Fait'), ('Non Applicable', 'Non Applicable')], max_length=20),
        ),
    ]
